### ISSUE TITLE
Delay for file selection at the start of Recording

### ISSUE THREAD

**Issue by esternin** [esternin/tkCam#4]
Phil did not expect the need to specify the save filename at the beginning of the record operation, "when you press record you expect recording to start immediately"

Could set the filename in a separate widget, but it's getting crowded, so a "config" menu or tab?

**Comment by esternin** [comment]
Perhaps the auto-save checkbutton as in  9175a2e666c8a9c9a4e46b51d145005cf556bb85 is good enough?

**Comment by fboseglav** [comment]
Looks good!
